version: "3.8"
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./server:/app
    environment:
      DB_URL: mongodb://${MONGO_ADMIN_USERNAME}:${MONGO_ADMIN_PASSWORD}@db/${MONGO_DATABASE}
      NODE_ENV: ${NODE_ENV_DEV}
      JWT_COOKIE_EXPIRE: ${JWT_COOKIE_EXPIRE}
      JWT_SECRET: ${JWT_SECRET}
    links:
      - db
  db:
    image: mongo:5.0.7-focal
    ports:
      - 27017:27017
    command: mongod
    container_name: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_USERNAME: ${MONGO_ADMIN_USERNAME}
      MONGO_PASSWORD: ${MONGO_ADMIN_PASSWORD}
    volumes:
      - agrostack:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
volumes:
  agrostack:
