version: "3.8"
services:
  backend:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5000:5000
    volumes:
      - ./server/public:/app/public
      - ./server/src:/app/src
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      DB_URL: mongodb://${PROD_MONGO_ADMIN_USERNAME}:${PROD_MONGO_ADMIN_PASSWORD}@db/${PROD_MONGO_DATABASE}
      NODE_ENV: ${NODE_ENV_PROD}
      JWT_COOKIE_EXPIRE: ${JWT_COOKIE_EXPIRE}
      JWT_SECRET: ${JWT_SECRET}
    links:
      - db
  db:
    image: mongo:5.0.7-focal
    ports:
      - 6044:27017
    command: mongod
    container_name: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${PROD_MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${PROD_MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${PROD_MONGO_DATABASE}
      MONGO_USERNAME: ${PROD_MONGO_ADMIN_USERNAME}
      MONGO_PASSWORD: ${PROD_MONGO_ADMIN_PASSWORD}
    volumes:
      - agrostack-prod:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
volumes:
  agrostack-prod:
