name: CICD pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: ramankarki/x7-backend

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: docker image build --tag $IMAGE_NAME:$GITHUB_RUN_ID --target prod .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: |
          docker push $IMAGE_NAME:$GITHUB_RUN_ID

      - name: Start ssh-agent
        run: eval "$(ssh-agent -s)"

      - name: Add private key to ssh-agent
        run: ssh-add ${{ secrets.SSH_PRIVATE }}

      - name: Enter passphrase for private key
        run: echo ${{ secrets.SSH_PHRASE }} | ssh-add -

      - name: Run commands on remote server
        run: ssh -i ${{ secrets.SSH_PRIVATE }} root@64.227.132.232 'docker service ls && whoami'
